baseURL = "/"
languageCode = "en-us"
title = "Kiana's World"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
customCss = []

[[menu.shortcuts]]
name = "Github"
url = "https://github.com/K-Winkles"
weight = 20

[[menu.shortcuts]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/kiana-alessandra/"
weight = 20

[[menu.shortcuts]]
name = "Steam"
url = "https://steamcommunity.com/id/kianalessandra/"
weight = 20
